# The number of inception modules
depth: 4
# The number of input dimensions
in_dim: 4
# The number of hidden dimensions
hidden_dim: 64
# The dimensionality of the bottleneck layer
bottleneck_dim: 32
# The base kernel size, the sizes of the kernels are computed as [base_kernel_size // (2 ** i) for i in range(3)]
base_kernel_size: 40
# Whether to use residual connections
use_residuals: True
# The learning rate
lr: 0.001
# The weight decay
wd: 0.001
# The number of semi-hard negatives to use in the triplet loss
# num_semi_hard_negatives: 128
# Whether to use in-triplet hard negative mining
anchor_swap: True
# The margin for the triplet loss
triplet_margin: 0.2
# Whether to normalize the output features to the unit hypersphere
normalize_output: False
# Which type of loss to use
loss_type: bce
# The number of hidden layers in the MLP classifier
n_hidden_clf_layers: 0
# The number of hidden dimensions in the MLP classifier
clf_hidden_dim: 64
