depth: 2
in_dim: 6
hidden_dim: 32
bottleneck_dim: 46
base_kernel_size: 32
use_residuals: True
lr: 0.001
wd: 0.001
# num_semi_hard_negatives: 128
anchor_swap: True
triplet_margin: 0.2
normalize_output: True
