channels:
  - time
  - position
  - drift
  - position_diff
  - drift_diff
  - target
compute_velocity:
  include_magnitude: false
normalization:
  saccade_amplitude:
    scaling_factor: 0.5
    lookup_samples: 10
    col_names:
      - position
      - drift
sanitation:
  trial:
    thresholds:
      position:
        max_value: 'auto'
        snr: 'auto'
        mean_vel: 'auto'
      drift:
        max_value: 'auto'
        snr: 'auto'
        mean_vel: 'auto'
  segment:
    thresholds:
      position:
        max_value: 'auto:1.94'
      drift:
        max_value: 'auto'
segmentation:
  sample_rate: 300 # Hz
  post_saccade_time_threshold: 1 # sec
  exclude_first: true
