sanitation:
  position_thresholds:
    max_value: 3.0
    mean_vel: 3.0
  drift_thresholds:
    max_value: 3.0
    mean_vel: 3.0
file_normalization:
  trailing_window_width: 150  # datapoints
  scaling_factor: 10
segmentation:
  post_saccade_time_threshold: 1
  exclude_first: true
  # invisible_target_mode: exclude
channels:
  - position
  - drift
  - position_velocity
  - drift_velocity
  - position_diff
  - drift_diff
