sanitation:
  position_thresholds:
    max_value: 3.0
    snr: 3.0
    mean_vel: 0.3
  drift_thresholds:
    max_value: 3.0
    snr: 3.0
    mean_vel: 0.3
file_normalization:
  trailing_window_width: 150  # datapoints
segmentation:
  post_saccade_time_threshold: 1
  exclude_first: true
channels:
  - position
  - drift
  - position_velocity
  - drift_velocity
  - position_diff
  - drift_diff
